// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: content/v1/content.proto

package content

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	v1 "ticktok-service/api/user/v1"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义核心实体 Video
type Video struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Author         *v1.User               `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	PlayUrl        string                 `protobuf:"bytes,3,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	CoverUrl       string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	FavoriteCount  int64                  `protobuf:"varint,5,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	CommentCount   int64                  `protobuf:"varint,6,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	IsFavorite     bool                   `protobuf:"varint,7,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	Title          string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	RecommendScore int32                  `protobuf:"varint,9,opt,name=recommend_score,json=recommendScore,proto3" json:"recommend_score,omitempty"` // 新增：推荐权重
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_content_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *Video) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetAuthor() *v1.User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Video) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Video) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *Video) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Video) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetRecommendScore() int32 {
	if x != nil {
		return x.RecommendScore
	}
	return 0
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *v1.User               `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateDate    string                 `protobuf:"bytes,4,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_content_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetCreateDate() string {
	if x != nil {
		return x.CreateDate
	}
	return ""
}

// Feed 接口
type GetFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastScore     int32                  `protobuf:"varint,1,opt,name=last_score,json=lastScore,proto3" json:"last_score,omitempty"` // 上一页最后一条视频的 recommend_score，第一页传 0
	LastId        int64                  `protobuf:"varint,2,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`          // 上一页最后一条视频的 ID，第一页传 0
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                           // 可选，用于判断用户是否点赞
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedRequest) Reset() {
	*x = GetFeedRequest{}
	mi := &file_content_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedRequest) ProtoMessage() {}

func (x *GetFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *GetFeedRequest) GetLastScore() int32 {
	if x != nil {
		return x.LastScore
	}
	return 0
}

func (x *GetFeedRequest) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *GetFeedRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	VideoList     []*Video               `protobuf:"bytes,3,rep,name=video_list,json=videoList,proto3" json:"video_list,omitempty"`
	NextScore     int32                  `protobuf:"varint,4,opt,name=next_score,json=nextScore,proto3" json:"next_score,omitempty"` // 返回给客户端的下一页 score 游标
	NextId        int64                  `protobuf:"varint,5,opt,name=next_id,json=nextId,proto3" json:"next_id,omitempty"`          // 返回给客户端的下一页 id 游标
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedResponse) Reset() {
	*x = GetFeedResponse{}
	mi := &file_content_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResponse) ProtoMessage() {}

func (x *GetFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResponse.ProtoReflect.Descriptor instead.
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *GetFeedResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetFeedResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetFeedResponse) GetVideoList() []*Video {
	if x != nil {
		return x.VideoList
	}
	return nil
}

func (x *GetFeedResponse) GetNextScore() int32 {
	if x != nil {
		return x.NextScore
	}
	return 0
}

func (x *GetFeedResponse) GetNextId() int64 {
	if x != nil {
		return x.NextId
	}
	return 0
}

// 视频发布 Step 1
type GetVideoUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoUploadURLRequest) Reset() {
	*x = GetVideoUploadURLRequest{}
	mi := &file_content_v1_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoUploadURLRequest) ProtoMessage() {}

func (x *GetVideoUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GetVideoUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{4}
}

func (x *GetVideoUploadURLRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *GetVideoUploadURLRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetVideoUploadURLRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetVideoUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,3,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"` // 预签名上传URL
	VideoId       int64                  `protobuf:"varint,4,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`      // 返回预先生成的视频ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoUploadURLResponse) Reset() {
	*x = GetVideoUploadURLResponse{}
	mi := &file_content_v1_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoUploadURLResponse) ProtoMessage() {}

func (x *GetVideoUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoUploadURLResponse.ProtoReflect.Descriptor instead.
func (*GetVideoUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{5}
}

func (x *GetVideoUploadURLResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetVideoUploadURLResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetVideoUploadURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetVideoUploadURLResponse) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

// 视频发布 Step 2
type PublishVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	PlayUrl       string                 `protobuf:"bytes,2,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`    // (可选)可以由服务端基于video_id拼接，或者客户端传
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"` // (可选)封面地址
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVideoRequest) Reset() {
	*x = PublishVideoRequest{}
	mi := &file_content_v1_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVideoRequest) ProtoMessage() {}

func (x *PublishVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVideoRequest.ProtoReflect.Descriptor instead.
func (*PublishVideoRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{6}
}

func (x *PublishVideoRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *PublishVideoRequest) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *PublishVideoRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *PublishVideoRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type PublishVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVideoResponse) Reset() {
	*x = PublishVideoResponse{}
	mi := &file_content_v1_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVideoResponse) ProtoMessage() {}

func (x *PublishVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVideoResponse.ProtoReflect.Descriptor instead.
func (*PublishVideoResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{7}
}

func (x *PublishVideoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PublishVideoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 获取发布列表
type GetPublishListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishListRequest) Reset() {
	*x = GetPublishListRequest{}
	mi := &file_content_v1_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishListRequest) ProtoMessage() {}

func (x *GetPublishListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishListRequest.ProtoReflect.Descriptor instead.
func (*GetPublishListRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{8}
}

func (x *GetPublishListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPublishListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetPublishListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	VideoList     []*Video               `protobuf:"bytes,3,rep,name=video_list,json=videoList,proto3" json:"video_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishListResponse) Reset() {
	*x = GetPublishListResponse{}
	mi := &file_content_v1_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishListResponse) ProtoMessage() {}

func (x *GetPublishListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishListResponse.ProtoReflect.Descriptor instead.
func (*GetPublishListResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{9}
}

func (x *GetPublishListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPublishListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetPublishListResponse) GetVideoList() []*Video {
	if x != nil {
		return x.VideoList
	}
	return nil
}

type FavoriteActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ActionType    int32                  `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // 1-like, 2-unlike
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteActionRequest) Reset() {
	*x = FavoriteActionRequest{}
	mi := &file_content_v1_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteActionRequest) ProtoMessage() {}

func (x *FavoriteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteActionRequest.ProtoReflect.Descriptor instead.
func (*FavoriteActionRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{10}
}

func (x *FavoriteActionRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *FavoriteActionRequest) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *FavoriteActionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type FavoriteActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteActionResponse) Reset() {
	*x = FavoriteActionResponse{}
	mi := &file_content_v1_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteActionResponse) ProtoMessage() {}

func (x *FavoriteActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteActionResponse.ProtoReflect.Descriptor instead.
func (*FavoriteActionResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{11}
}

func (x *FavoriteActionResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FavoriteActionResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CommentActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ActionType    int32                  `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // 1-create, 2-delete
	CommentText   string                 `protobuf:"bytes,3,opt,name=comment_text,json=commentText,proto3" json:"comment_text,omitempty"`
	CommentId     int64                  `protobuf:"varint,4,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentActionRequest) Reset() {
	*x = CommentActionRequest{}
	mi := &file_content_v1_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentActionRequest) ProtoMessage() {}

func (x *CommentActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentActionRequest.ProtoReflect.Descriptor instead.
func (*CommentActionRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{12}
}

func (x *CommentActionRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CommentActionRequest) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *CommentActionRequest) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

func (x *CommentActionRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *CommentActionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CommentActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Comment       *Comment               `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentActionResponse) Reset() {
	*x = CommentActionResponse{}
	mi := &file_content_v1_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentActionResponse) ProtoMessage() {}

func (x *CommentActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentActionResponse.ProtoReflect.Descriptor instead.
func (*CommentActionResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{13}
}

func (x *CommentActionResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommentActionResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CommentActionResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type GetCommentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentListRequest) Reset() {
	*x = GetCommentListRequest{}
	mi := &file_content_v1_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListRequest) ProtoMessage() {}

func (x *GetCommentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListRequest.ProtoReflect.Descriptor instead.
func (*GetCommentListRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{14}
}

func (x *GetCommentListRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *GetCommentListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetCommentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	CommentList   []*Comment             `protobuf:"bytes,3,rep,name=comment_list,json=commentList,proto3" json:"comment_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentListResponse) Reset() {
	*x = GetCommentListResponse{}
	mi := &file_content_v1_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListResponse) ProtoMessage() {}

func (x *GetCommentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListResponse.ProtoReflect.Descriptor instead.
func (*GetCommentListResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_content_proto_rawDescGZIP(), []int{15}
}

func (x *GetCommentListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCommentListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetCommentListResponse) GetCommentList() []*Comment {
	if x != nil {
		return x.CommentList
	}
	return nil
}

var File_content_v1_content_proto protoreflect.FileDescriptor

const file_content_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x18content/v1/content.proto\x12\n" +
	"content.v1\x1a\x12user/v1/user.proto\"\xa2\x02\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x06author\x18\x02 \x01(\v2\r.user.v1.UserR\x06author\x12\x19\n" +
	"\bplay_url\x18\x03 \x01(\tR\aplayUrl\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12%\n" +
	"\x0efavorite_count\x18\x05 \x01(\x03R\rfavoriteCount\x12#\n" +
	"\rcomment_count\x18\x06 \x01(\x03R\fcommentCount\x12\x1f\n" +
	"\vis_favorite\x18\a \x01(\bR\n" +
	"isFavorite\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12'\n" +
	"\x0frecommend_score\x18\t \x01(\x05R\x0erecommendScore\"w\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\x04user\x18\x02 \x01(\v2\r.user.v1.UserR\x04user\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vcreate_date\x18\x04 \x01(\tR\n" +
	"createDate\"^\n" +
	"\x0eGetFeedRequest\x12\x1d\n" +
	"\n" +
	"last_score\x18\x01 \x01(\x05R\tlastScore\x12\x17\n" +
	"\alast_id\x18\x02 \x01(\x03R\x06lastId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\xa1\x01\n" +
	"\x0fGetFeedResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x120\n" +
	"\n" +
	"video_list\x18\x03 \x03(\v2\x11.content.v1.VideoR\tvideoList\x12\x1d\n" +
	"\n" +
	"next_score\x18\x04 \x01(\x05R\tnextScore\x12\x17\n" +
	"\anext_id\x18\x05 \x01(\x03R\x06nextId\"c\n" +
	"\x18GetVideoUploadURLRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"{\n" +
	"\x19GetVideoUploadURLResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x03 \x01(\tR\tuploadUrl\x12\x19\n" +
	"\bvideo_id\x18\x04 \x01(\x03R\avideoId\"~\n" +
	"\x13PublishVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x19\n" +
	"\bplay_url\x18\x02 \x01(\tR\aplayUrl\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"<\n" +
	"\x14PublishVideoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"F\n" +
	"\x15GetPublishListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"p\n" +
	"\x16GetPublishListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x120\n" +
	"\n" +
	"video_list\x18\x03 \x03(\v2\x11.content.v1.VideoR\tvideoList\"i\n" +
	"\x15FavoriteActionRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\x05R\n" +
	"actionType\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\">\n" +
	"\x16FavoriteActionResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xaa\x01\n" +
	"\x14CommentActionRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\x05R\n" +
	"actionType\x12!\n" +
	"\fcomment_text\x18\x03 \x01(\tR\vcommentText\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x04 \x01(\x03R\tcommentId\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\"l\n" +
	"\x15CommentActionResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12-\n" +
	"\acomment\x18\x03 \x01(\v2\x13.content.v1.CommentR\acomment\"H\n" +
	"\x15GetCommentListRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"v\n" +
	"\x16GetCommentListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x126\n" +
	"\fcomment_list\x18\x03 \x03(\v2\x13.content.v1.CommentR\vcommentList2\xea\x04\n" +
	"\x0eContentService\x12B\n" +
	"\aGetFeed\x12\x1a.content.v1.GetFeedRequest\x1a\x1b.content.v1.GetFeedResponse\x12`\n" +
	"\x11GetVideoUploadURL\x12$.content.v1.GetVideoUploadURLRequest\x1a%.content.v1.GetVideoUploadURLResponse\x12Q\n" +
	"\fPublishVideo\x12\x1f.content.v1.PublishVideoRequest\x1a .content.v1.PublishVideoResponse\x12W\n" +
	"\x0eGetPublishList\x12!.content.v1.GetPublishListRequest\x1a\".content.v1.GetPublishListResponse\x12W\n" +
	"\x0eFavoriteAction\x12!.content.v1.FavoriteActionRequest\x1a\".content.v1.FavoriteActionResponse\x12T\n" +
	"\rCommentAction\x12 .content.v1.CommentActionRequest\x1a!.content.v1.CommentActionResponse\x12W\n" +
	"\x0eGetCommentList\x12!.content.v1.GetCommentListRequest\x1a\".content.v1.GetCommentListResponseB(Z&ticktok-service/api/content/v1;contentb\x06proto3"

var (
	file_content_v1_content_proto_rawDescOnce sync.Once
	file_content_v1_content_proto_rawDescData []byte
)

func file_content_v1_content_proto_rawDescGZIP() []byte {
	file_content_v1_content_proto_rawDescOnce.Do(func() {
		file_content_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_v1_content_proto_rawDesc), len(file_content_v1_content_proto_rawDesc)))
	})
	return file_content_v1_content_proto_rawDescData
}

var file_content_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_content_v1_content_proto_goTypes = []any{
	(*Video)(nil),                     // 0: content.v1.Video
	(*Comment)(nil),                   // 1: content.v1.Comment
	(*GetFeedRequest)(nil),            // 2: content.v1.GetFeedRequest
	(*GetFeedResponse)(nil),           // 3: content.v1.GetFeedResponse
	(*GetVideoUploadURLRequest)(nil),  // 4: content.v1.GetVideoUploadURLRequest
	(*GetVideoUploadURLResponse)(nil), // 5: content.v1.GetVideoUploadURLResponse
	(*PublishVideoRequest)(nil),       // 6: content.v1.PublishVideoRequest
	(*PublishVideoResponse)(nil),      // 7: content.v1.PublishVideoResponse
	(*GetPublishListRequest)(nil),     // 8: content.v1.GetPublishListRequest
	(*GetPublishListResponse)(nil),    // 9: content.v1.GetPublishListResponse
	(*FavoriteActionRequest)(nil),     // 10: content.v1.FavoriteActionRequest
	(*FavoriteActionResponse)(nil),    // 11: content.v1.FavoriteActionResponse
	(*CommentActionRequest)(nil),      // 12: content.v1.CommentActionRequest
	(*CommentActionResponse)(nil),     // 13: content.v1.CommentActionResponse
	(*GetCommentListRequest)(nil),     // 14: content.v1.GetCommentListRequest
	(*GetCommentListResponse)(nil),    // 15: content.v1.GetCommentListResponse
	(*v1.User)(nil),                   // 16: user.v1.User
}
var file_content_v1_content_proto_depIdxs = []int32{
	16, // 0: content.v1.Video.author:type_name -> user.v1.User
	16, // 1: content.v1.Comment.user:type_name -> user.v1.User
	0,  // 2: content.v1.GetFeedResponse.video_list:type_name -> content.v1.Video
	0,  // 3: content.v1.GetPublishListResponse.video_list:type_name -> content.v1.Video
	1,  // 4: content.v1.CommentActionResponse.comment:type_name -> content.v1.Comment
	1,  // 5: content.v1.GetCommentListResponse.comment_list:type_name -> content.v1.Comment
	2,  // 6: content.v1.ContentService.GetFeed:input_type -> content.v1.GetFeedRequest
	4,  // 7: content.v1.ContentService.GetVideoUploadURL:input_type -> content.v1.GetVideoUploadURLRequest
	6,  // 8: content.v1.ContentService.PublishVideo:input_type -> content.v1.PublishVideoRequest
	8,  // 9: content.v1.ContentService.GetPublishList:input_type -> content.v1.GetPublishListRequest
	10, // 10: content.v1.ContentService.FavoriteAction:input_type -> content.v1.FavoriteActionRequest
	12, // 11: content.v1.ContentService.CommentAction:input_type -> content.v1.CommentActionRequest
	14, // 12: content.v1.ContentService.GetCommentList:input_type -> content.v1.GetCommentListRequest
	3,  // 13: content.v1.ContentService.GetFeed:output_type -> content.v1.GetFeedResponse
	5,  // 14: content.v1.ContentService.GetVideoUploadURL:output_type -> content.v1.GetVideoUploadURLResponse
	7,  // 15: content.v1.ContentService.PublishVideo:output_type -> content.v1.PublishVideoResponse
	9,  // 16: content.v1.ContentService.GetPublishList:output_type -> content.v1.GetPublishListResponse
	11, // 17: content.v1.ContentService.FavoriteAction:output_type -> content.v1.FavoriteActionResponse
	13, // 18: content.v1.ContentService.CommentAction:output_type -> content.v1.CommentActionResponse
	15, // 19: content.v1.ContentService.GetCommentList:output_type -> content.v1.GetCommentListResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_content_v1_content_proto_init() }
func file_content_v1_content_proto_init() {
	if File_content_v1_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_v1_content_proto_rawDesc), len(file_content_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_content_v1_content_proto_goTypes,
		DependencyIndexes: file_content_v1_content_proto_depIdxs,
		MessageInfos:      file_content_v1_content_proto_msgTypes,
	}.Build()
	File_content_v1_content_proto = out.File
	file_content_v1_content_proto_goTypes = nil
	file_content_v1_content_proto_depIdxs = nil
}
