apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: ticktok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ticktok-worker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ticktok-config
            - secretRef:
                name: ticktok-secret
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
