version: "3"

services:
  mysql:
    image: docker.1ms.run/mysql:8.0
    container_name: ticktok-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ugchan123456
      MYSQL_DATABASE: ticktok
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql

  redis:
    image: docker.1ms.run/redis:alpine
    container_name: ticktok-redis
    ports:
      - "16379:6379"

  minio:
    image: docker.1ms.run/minio/minio
    container_name: ticktok-minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: ugchan123456
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - ../data/minio:/data

  etcd:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/bitnami/etcd:latest
    container_name: ticktok-etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"

  prometheus:
    image: docker.1ms.run/prom/prometheus
    container_name: ticktok-prometheus
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19091:9090"

  grafana:
    image: docker.1ms.run/grafana/grafana
    container_name: ticktok-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
