apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: infra
spec:
  ports:
    - port: 3000
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: infra
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: docker.1ms.run/grafana/grafana
          ports:
            - containerPort: 3000
