// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: chatbot/v1/chatbot.proto

package chatbot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInput     string                 `protobuf:"bytes,1,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_chatbot_v1_chatbot_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

func (x *ChatRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_chatbot_v1_chatbot_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_chatbot_v1_chatbot_proto protoreflect.FileDescriptor

const file_chatbot_v1_chatbot_proto_rawDesc = "" +
	"\n" +
	"\x18chatbot/v1/chatbot.proto\x12\n" +
	"chatbot.v1\"E\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"user_input\x18\x01 \x01(\tR\tuserInput\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"$\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply2K\n" +
	"\x0eChatbotService\x129\n" +
	"\x04Chat\x12\x17.chatbot.v1.ChatRequest\x1a\x18.chatbot.v1.ChatResponseB(Z&ticktok-service/api/chatbot/v1;chatbotb\x06proto3"

var (
	file_chatbot_v1_chatbot_proto_rawDescOnce sync.Once
	file_chatbot_v1_chatbot_proto_rawDescData []byte
)

func file_chatbot_v1_chatbot_proto_rawDescGZIP() []byte {
	file_chatbot_v1_chatbot_proto_rawDescOnce.Do(func() {
		file_chatbot_v1_chatbot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatbot_v1_chatbot_proto_rawDesc), len(file_chatbot_v1_chatbot_proto_rawDesc)))
	})
	return file_chatbot_v1_chatbot_proto_rawDescData
}

var file_chatbot_v1_chatbot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chatbot_v1_chatbot_proto_goTypes = []any{
	(*ChatRequest)(nil),  // 0: chatbot.v1.ChatRequest
	(*ChatResponse)(nil), // 1: chatbot.v1.ChatResponse
}
var file_chatbot_v1_chatbot_proto_depIdxs = []int32{
	0, // 0: chatbot.v1.ChatbotService.Chat:input_type -> chatbot.v1.ChatRequest
	1, // 1: chatbot.v1.ChatbotService.Chat:output_type -> chatbot.v1.ChatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatbot_v1_chatbot_proto_init() }
func file_chatbot_v1_chatbot_proto_init() {
	if File_chatbot_v1_chatbot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatbot_v1_chatbot_proto_rawDesc), len(file_chatbot_v1_chatbot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatbot_v1_chatbot_proto_goTypes,
		DependencyIndexes: file_chatbot_v1_chatbot_proto_depIdxs,
		MessageInfos:      file_chatbot_v1_chatbot_proto_msgTypes,
	}.Build()
	File_chatbot_v1_chatbot_proto = out.File
	file_chatbot_v1_chatbot_proto_goTypes = nil
	file_chatbot_v1_chatbot_proto_depIdxs = nil
}
