// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: chatbot/v1/chatbot.proto

package chatbot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_chatbot_v1_chatbot_proto_rawDescGZIP(), []int{0}
}

func (x *CreateConversationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateConversationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationResponse) Reset() {
	*x = CreateConversationResponse{}
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationResponse) ProtoMessage() {}

func (x *CreateConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationResponse.ProtoReflect.Descriptor instead.
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return file_chatbot_v1_chatbot_proto_rawDescGZIP(), []int{1}
}

func (x *CreateConversationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chatbot_v1_chatbot_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Temperature   float64                `protobuf:"fixed64,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamRequest) Reset() {
	*x = ChatStreamRequest{}
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamRequest) ProtoMessage() {}

func (x *ChatStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamRequest.ProtoReflect.Descriptor instead.
func (*ChatStreamRequest) Descriptor() ([]byte, []int) {
	return file_chatbot_v1_chatbot_proto_rawDescGZIP(), []int{3}
}

func (x *ChatStreamRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatStreamRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatStreamRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatStreamRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type ChatStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentChunk  string                 `protobuf:"bytes,1,opt,name=content_chunk,json=contentChunk,proto3" json:"content_chunk,omitempty"`
	IsFinish      bool                   `protobuf:"varint,2,opt,name=is_finish,json=isFinish,proto3" json:"is_finish,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamResponse) Reset() {
	*x = ChatStreamResponse{}
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamResponse) ProtoMessage() {}

func (x *ChatStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamResponse.ProtoReflect.Descriptor instead.
func (*ChatStreamResponse) Descriptor() ([]byte, []int) {
	return file_chatbot_v1_chatbot_proto_rawDescGZIP(), []int{4}
}

func (x *ChatStreamResponse) GetContentChunk() string {
	if x != nil {
		return x.ContentChunk
	}
	return ""
}

func (x *ChatStreamResponse) GetIsFinish() bool {
	if x != nil {
		return x.IsFinish
	}
	return false
}

func (x *ChatStreamResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type GetChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chatbot_v1_chatbot_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatHistoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryResponse) Reset() {
	*x = GetChatHistoryResponse{}
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryResponse) ProtoMessage() {}

func (x *GetChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chatbot_v1_chatbot_proto_rawDescGZIP(), []int{6}
}

func (x *GetChatHistoryResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_chatbot_v1_chatbot_proto_rawDescGZIP(), []int{7}
}

func (x *ListConversationsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ConversationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationInfo) Reset() {
	*x = ConversationInfo{}
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationInfo) ProtoMessage() {}

func (x *ConversationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationInfo.ProtoReflect.Descriptor instead.
func (*ConversationInfo) Descriptor() ([]byte, []int) {
	return file_chatbot_v1_chatbot_proto_rawDescGZIP(), []int{8}
}

func (x *ConversationInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConversationInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConversationInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*ConversationInfo    `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_v1_chatbot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_chatbot_v1_chatbot_proto_rawDescGZIP(), []int{9}
}

func (x *ListConversationsResponse) GetConversations() []*ConversationInfo {
	if x != nil {
		return x.Conversations
	}
	return nil
}

var File_chatbot_v1_chatbot_proto protoreflect.FileDescriptor

const file_chatbot_v1_chatbot_proto_rawDesc = "" +
	"\n" +
	"\x18chatbot/v1/chatbot.proto\x12\n" +
	"chatbot.v1\"J\n" +
	"\x19CreateConversationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\";\n" +
	"\x1aCreateConversationResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xb8\x01\n" +
	"\x11ChatStreamRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x123\n" +
	"\bmessages\x18\x02 \x03(\v2\x17.chatbot.v1.ChatMessageR\bmessages\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x01R\vtemperature\"{\n" +
	"\x12ChatStreamResponse\x12#\n" +
	"\rcontent_chunk\x18\x01 \x01(\tR\fcontentChunk\x12\x1b\n" +
	"\tis_finish\x18\x02 \x01(\bR\bisFinish\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"6\n" +
	"\x15GetChatHistoryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"M\n" +
	"\x16GetChatHistoryResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.chatbot.v1.ChatMessageR\bmessages\"3\n" +
	"\x18ListConversationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"f\n" +
	"\x10ConversationInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"_\n" +
	"\x19ListConversationsResponse\x12B\n" +
	"\rconversations\x18\x01 \x03(\v2\x1c.chatbot.v1.ConversationInfoR\rconversations2\xff\x02\n" +
	"\x0eChatbotService\x12M\n" +
	"\n" +
	"ChatStream\x12\x1d.chatbot.v1.ChatStreamRequest\x1a\x1e.chatbot.v1.ChatStreamResponse0\x01\x12W\n" +
	"\x0eGetChatHistory\x12!.chatbot.v1.GetChatHistoryRequest\x1a\".chatbot.v1.GetChatHistoryResponse\x12`\n" +
	"\x11ListConversations\x12$.chatbot.v1.ListConversationsRequest\x1a%.chatbot.v1.ListConversationsResponse\x12c\n" +
	"\x12CreateConversation\x12%.chatbot.v1.CreateConversationRequest\x1a&.chatbot.v1.CreateConversationResponseB(Z&ticktok-service/api/chatbot/v1;chatbotb\x06proto3"

var (
	file_chatbot_v1_chatbot_proto_rawDescOnce sync.Once
	file_chatbot_v1_chatbot_proto_rawDescData []byte
)

func file_chatbot_v1_chatbot_proto_rawDescGZIP() []byte {
	file_chatbot_v1_chatbot_proto_rawDescOnce.Do(func() {
		file_chatbot_v1_chatbot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatbot_v1_chatbot_proto_rawDesc), len(file_chatbot_v1_chatbot_proto_rawDesc)))
	})
	return file_chatbot_v1_chatbot_proto_rawDescData
}

var file_chatbot_v1_chatbot_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chatbot_v1_chatbot_proto_goTypes = []any{
	(*CreateConversationRequest)(nil),  // 0: chatbot.v1.CreateConversationRequest
	(*CreateConversationResponse)(nil), // 1: chatbot.v1.CreateConversationResponse
	(*ChatMessage)(nil),                // 2: chatbot.v1.ChatMessage
	(*ChatStreamRequest)(nil),          // 3: chatbot.v1.ChatStreamRequest
	(*ChatStreamResponse)(nil),         // 4: chatbot.v1.ChatStreamResponse
	(*GetChatHistoryRequest)(nil),      // 5: chatbot.v1.GetChatHistoryRequest
	(*GetChatHistoryResponse)(nil),     // 6: chatbot.v1.GetChatHistoryResponse
	(*ListConversationsRequest)(nil),   // 7: chatbot.v1.ListConversationsRequest
	(*ConversationInfo)(nil),           // 8: chatbot.v1.ConversationInfo
	(*ListConversationsResponse)(nil),  // 9: chatbot.v1.ListConversationsResponse
}
var file_chatbot_v1_chatbot_proto_depIdxs = []int32{
	2, // 0: chatbot.v1.ChatStreamRequest.messages:type_name -> chatbot.v1.ChatMessage
	2, // 1: chatbot.v1.GetChatHistoryResponse.messages:type_name -> chatbot.v1.ChatMessage
	8, // 2: chatbot.v1.ListConversationsResponse.conversations:type_name -> chatbot.v1.ConversationInfo
	3, // 3: chatbot.v1.ChatbotService.ChatStream:input_type -> chatbot.v1.ChatStreamRequest
	5, // 4: chatbot.v1.ChatbotService.GetChatHistory:input_type -> chatbot.v1.GetChatHistoryRequest
	7, // 5: chatbot.v1.ChatbotService.ListConversations:input_type -> chatbot.v1.ListConversationsRequest
	0, // 6: chatbot.v1.ChatbotService.CreateConversation:input_type -> chatbot.v1.CreateConversationRequest
	4, // 7: chatbot.v1.ChatbotService.ChatStream:output_type -> chatbot.v1.ChatStreamResponse
	6, // 8: chatbot.v1.ChatbotService.GetChatHistory:output_type -> chatbot.v1.GetChatHistoryResponse
	9, // 9: chatbot.v1.ChatbotService.ListConversations:output_type -> chatbot.v1.ListConversationsResponse
	1, // 10: chatbot.v1.ChatbotService.CreateConversation:output_type -> chatbot.v1.CreateConversationResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chatbot_v1_chatbot_proto_init() }
func file_chatbot_v1_chatbot_proto_init() {
	if File_chatbot_v1_chatbot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatbot_v1_chatbot_proto_rawDesc), len(file_chatbot_v1_chatbot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatbot_v1_chatbot_proto_goTypes,
		DependencyIndexes: file_chatbot_v1_chatbot_proto_depIdxs,
		MessageInfos:      file_chatbot_v1_chatbot_proto_msgTypes,
	}.Build()
	File_chatbot_v1_chatbot_proto = out.File
	file_chatbot_v1_chatbot_proto_goTypes = nil
	file_chatbot_v1_chatbot_proto_depIdxs = nil
}
